      SUBROUTINE MAX_CONECT
     &          (KXX     ,LMXNDL ,LNNDL    ,MAINF   ,MAXNB   ,NUMEL
     &          ,NUMNP)

      IMPLICIT NONE
      
      INTEGER*4::I, INODE, L, LMXNDL, MAX_CON,NNUD, NUMEL,NUMNP
     ;           ,MAINF,MAXNB
      INTEGER*4::KXX(LMXNDL,NUMEL),LNNDL(NUMEL)

      INTEGER*4,ALLOCATABLE::NOD_CONECT(:)

      ALLOCATE(NOD_CONECT(NUMNP))

      NOD_CONECT = 0

      DO L=1,NUMEL

          NNUD=LNNDL(L)

          DO I=1,NNUD
              
              INODE = KXX(I,L)
              NOD_CONECT(INODE) = NOD_CONECT (INODE) + 1

          END DO !INODE
      END DO !L

      MAX_CON = MAXVAL(NOD_CONECT)

      DEALLOCATE(NOD_CONECT)

	IF (MAX_CON.NE.MAXNB) THEN
		PRINT*,""
		PRINT*, "WRONG MAXIMUM NODE CONECTIVITTY: ", MAXNB
	    PRINT*, "MAXIMUN NODE CONECTIVITTY IS: ",MAX_CON
		WRITE(MAINF,*),""
		WRITE(MAINF,*), "WRONG MAXIMUM NODE CONECTIVITTY: ", MAXNB
	    WRITE(MAINF,*), "MAXIMUN NODE CONECTIVITTY IS: ",MAX_CON
	    IF (MAX_CON.GT.MAXNB) STOP 'MAXNB TOO SMALL'
	END IF

      END SUBROUTINE MAX_CONECT